// A huge list of calculus and linear algebra problems.
// Format: { id, topic, difficulty, problem, answer }
// Difficulty is an ELO-style rating from ~1000 to ~3000.
// MATH is wrapped in $...$ for KaTeX rendering.

export const mathProblems = [
  // --- Calculus I: Derivatives ---

  {
    id: "C01",
    topic: "Calculus (Basic Derivative)",
    difficulty: 1100,
    problem: "Let $f(x) = 5x^3 - 7x^2 + 2x - 10$. Find the value of $f'(2)$.",
    answer: "34",
  },
  {
    id: "C02",
    topic: "Calculus (Product Rule)",
    difficulty: 1350,
    problem: "Let $h(x) = x^2 \\cdot \\sin(x)$. Find the value of $h'(\\pi)$.",
    answer: "-π²",
  },
  {
    id: "C03",
    topic: "Calculus (Quotient Rule)",
    difficulty: 1450,
    problem: "Let $f(x) = \\frac{2x - 1}{x^2 + 1}$. Find the value of $f'(1)$.",
    answer: "0.5",
  },
  {
    id: "C04",
    topic: "Calculus (Chain Rule)",
    difficulty: 1500,
    problem: "Let $g(x) = (x^3 + 3)^4$. Find the value of $g'(1)$.",
    answer: "768",
  },
  {
    id: "C05",
    topic: "Calculus (Chain Rule with Trig)",
    difficulty: 1600,
    problem: "Let $f(x) = \\cos(\\pi x^2)$. Find the value of $f'(1)$.",
    answer: "0",
  },
  {
    id: "C06",
    topic: "Calculus (Implicit Differentiation)",
    difficulty: 1850,
    problem: "For the circle defined by $x^2 + y^2 = 25$, find the slope of the tangent line ($\\frac{dy}{dx}$) at the point $(3, -4)$.",
    answer: "0.75",
  },
  {
    id: "C36",
    topic: "Calculus (Related Rates)",
    difficulty: 1850,
    problem: "A spherical balloon is being inflated. Its radius is increasing at a rate of 2 cm/s. At the instant the radius is 10 cm, how fast is the volume of the balloon increasing in cm³/s? (Volume of a sphere is $V = \\frac{4}{3}\\pi r^3$)",
    answer: "800π",
  },
  {
    id: "C37",
    topic: "Calculus (Optimization)",
    difficulty: 1950,
    problem: "You have 100 meters of fencing to build a rectangular enclosure. What is the maximum possible area of the enclosure in square meters?",
    answer: "625",
  },
  {
    id: "C38",
    topic: "Calculus (Mean Value Theorem)",
    difficulty: 1750,
    problem: "For the function $f(x) = x^3 - 3x$ on the interval $[0, 3]$, find the value of $c$ that satisfies the Mean Value Theorem.",
    answer: "√3",
  },
  {
    id: "C39",
    topic: "Calculus (Chain & Product Rule)",
    difficulty: 1700,
    problem: "Let $f(x) = e^{2x} \\sin(3x)$. Find the value of $f'(0)$.",
    answer: "3",
  },
  {
    id: "C40",
    topic: "Calculus (Derivative of Inverse Trig)",
    difficulty: 1600,
    problem: "Let $f(x) = \\arctan(x^2)$. Find $f'(1)$.",
    answer: "1",
  },
  {
    id: "C51",
    topic: "Calculus (Limit by Factoring)",
    difficulty: 1150,
    problem: "Evaluate the limit: $\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$.",
    answer: "4",
  },
  {
    id: "C52",
    topic: "Calculus (Limit at Infinity)",
    difficulty: 1300,
    problem: "Evaluate the limit: $\\lim_{x \\to \\infty} \\frac{3x^2 - 5x + 2}{7x^2 + 4x - 1}$.",
    answer: "3/7",
  },
  {
    id: "C53",
    topic: "Calculus (Higher-Order Derivative)",
    difficulty: 1250,
    problem: "Let $f(x) = \\sin(x)$. Find the fourth derivative, $f^{(4)}(x)$.",
    answer: "sin(x)",
  },
  {
    id: "C54",
    topic: "Calculus (Equation of a Tangent Line)",
    difficulty: 1400,
    problem: "Find the y-intercept of the tangent line to the curve $y = x^3$ at the point $x=2$.",
    answer: "-16",
  },
  {
    id: "C55",
    topic: "Calculus (Chain Rule with Logs)",
    difficulty: 1550,
    problem: "Let $f(x) = \\ln(\\cos(x))$. Find $f'(\\pi/4)$.",
    answer: "-1",
  },
  {
    id: "C56",
    topic: "Calculus (Critical Points)",
    difficulty: 1350,
    problem: "Find the largest x-coordinate of a critical point for the function $f(x) = x^3 - 6x^2 + 5$.",
    answer: "4",
  },
  {
    id: "C57",
    topic: "Calculus (Concavity)",
    difficulty: 1600,
    problem: "Let $f(x) = xe^x$. On what interval is the function concave up?",
    answer: "(-2, ∞)",
  },
  {
    id: "C58",
    topic: "Calculus (Derivative of an Inverse)",
    difficulty: 2000,
    problem: "Let $f(x) = x^5 + x + 1$. Find the value of $(f^{-1})'(3)$.",
    answer: "1/6",
  },
  {
    id: "C59",
    topic: "Calculus (Related Rates - Ladder)",
    difficulty: 1900,
    problem: "A 10-foot ladder is leaning against a wall. The base of the ladder is sliding away from the wall at a rate of 2 ft/s. How fast is the top of the ladder sliding down the wall (in ft/s) when the base is 6 feet from the wall? Give the absolute value.",
    answer: "1.5",
  },
  {
    id: "C60",
    topic: "Calculus (Optimization - Box)",
    difficulty: 2050,
    problem: "An open-top box is to be made by cutting small congruent squares from the corners of a 12-inch-by-12-inch sheet of tin and bending up the sides. What is the side length of the squares that should be cut out to make the volume of the box as large as possible?",
    answer: "2",
  },
  {
    id: "C61",
    topic: "Calculus (L'Hôpital's Rule Indeterminate Power)",
    difficulty: 2200,
    problem: "Evaluate the limit $\\lim_{x \\to \\infty} (1 + \\frac{2}{x})^x$.",
    answer: "e²",
  },
  {
    id: "C62",
    topic: "Calculus (Product Rule - 3 functions)",
    difficulty: 1650,
    problem: "Let $f(x) = x \\cdot e^x \\cdot \\cos(x)$. Find $f'(0)$.",
    answer: "1",
  },
{
  id: "C97",
  topic: "Calculus (Basic Derivative)",
  difficulty: 1100,
  problem: "Let $f(x) = 2x^{-3} + \\sqrt{x}$. Find $f'(x)$.",
  answer: "-6x⁻⁴ + (1/2)x⁻¹/²",
},
{
  id: "C98",
  topic: "Calculus (Basic Derivative)",
  difficulty: 1200,
  problem: "Let $g(t) = 3e^t - \\tan(t)$. Find $g'(0)$.",
  answer: "2",
},
{
  id: "C99",
  topic: "Calculus (Product Rule)",
  difficulty: 1400,
  problem: "Let $f(x) = x^3 \\ln(x)$. Find $f'(e)$.",
  answer: "4e²",
},
{
  id: "C100",
  topic: "Calculus (Quotient Rule)",
  difficulty: 1500,
  problem: "Let $h(x) = \\frac{e^x}{x^2+1}$. Find the value of $h'(0)$.",
  answer: "1",
},
{
  id: "C101",
  topic: "Calculus (Chain Rule)",
  difficulty: 1450,
  problem: "Let $f(x) = \\sqrt{x^2+9}$. Find $f'(4)$.",
  answer: "0.8",
},
{
  id: "C102",
  topic: "Calculus (Definition of Derivative)",
  difficulty: 1650,
  problem: "Use the limit definition of the derivative to find $f'(x)$ for $f(x) = 2x^2$. Evaluate the limit $\\lim_{h \\to 0} \\frac{2(x+h)^2 - 2x^2}{h}$.",
  answer: "4x",
},
{
  id: "C103",
  topic: "Calculus (Chain Rule with Trig)",
  difficulty: 1600,
  problem: "Let $g(x) = \\sin^3(x)$. Find $g'(\\pi/3)$.",
  answer: "9/8",
},
{
  id: "C104",
  topic: "Calculus (Implicit Differentiation)",
  difficulty: 1900,
  problem: "For the curve defined by $xy + y^2 = 3$, find $\\frac{dy}{dx}$ at the point $(2, 1)$.",
  answer: "-0.25",
},
{
  id: "C105",
  topic: "Calculus (Higher-Order Derivative)",
  difficulty: 1550,
  problem: "Let $f(x) = x^2e^x$. Find the second derivative, $f''(x)$, and evaluate it at $x=0$.",
  answer: "2",
},
{
  id: "C106",
  topic: "Calculus (Horizontal Tangents)",
  difficulty: 1700,
  problem: "Find the smallest positive x-value where the function $f(x) = x + \\cos(x)$ has a horizontal tangent line.",
  answer: "π/2",
},
{
  id: "C107",
  topic: "Calculus (Related Rates)",
  difficulty: 2000,
  problem: "Water is leaking out of an inverted conical tank at a rate of 10,000 cm³/min. The tank has a height of 6m and a base radius of 2m. How fast is the water level falling when the water is 3m deep? (Use 1m = 100cm).",
  answer: "10/π cm/min",
},
{
  id: "C108",
  topic: "Calculus (Optimization)",
  difficulty: 2100,
  problem: "Find the point on the line $y=2x+3$ that is closest to the origin $(0,0)$. What is the x-coordinate of this point?",
  answer: "-1.2",
},
{
  id: "C109",
  topic: "Calculus (L'Hôpital's Rule)",
  difficulty: 1850,
  problem: "Evaluate the limit $\\lim_{x \\to 1} \\frac{\\ln(x)}{x-1}$.",
  answer: "1",
},
{
  id: "C110",
  topic: "Calculus (Logarithmic Differentiation)",
  difficulty: 2200,
  problem: "Let $y = x^x$. Find the value of $\\frac{dy}{dx}$ at $x=e$.",
  answer: "2e^e",
},
{
  id: "C111",
  topic: "Calculus (Equation of a Normal Line)",
  difficulty: 1750,
  problem: "Find the slope of the normal line to the curve $y = 1/x$ at $x=2$.",
  answer: "4",
},
{
  id: "C112",
  topic: "Calculus (FTC Part 1 with Chain Rule)",
  difficulty: 2250,
  problem: "Let $g(x) = \\int_0^{x^2} \\cos(t) dt$. Find $g'(\\sqrt{\\pi})$.",
  answer: "-2√π",
},
{
  id: "C113",
  topic: "Calculus (Finding Inflection Points)",
  difficulty: 1800,
  problem: "Find the x-coordinate of the inflection point of the curve $f(x) = x^3 - 3x^2 + 2x + 5$.",
  answer: "1",
},
{
  id: "C114",
  topic: "Calculus (Differentiability)",
  difficulty: 1950,
  problem: "For what value of 'a' is the function $f(x) = \\begin{cases} x^2, & x \\le 2 \\\\ ax-4, & x > 2 \\end{cases}$ differentiable everywhere?",
  answer: "4",
},
{
  id: "C115",
  topic: "Calculus (Linear Approximation)",
  difficulty: 1700,
  problem: "Use a linear approximation of $f(x) = \\sqrt{x}$ at $x=100$ to estimate the value of $\\sqrt{101}$.",
  answer: "10.05",
},
{
  id: "C116",
  topic: "Calculus (Second Derivative Implicit)",
  difficulty: 2400,
  problem: "For the circle $x^2+y^2=25$, find the value of the second derivative, $\\frac{d^2y}{dx^2}$, at the point $(0, 5)$.",
  answer: "-0.2",
},



  // --- Calculus II: Integrals ---



  {
    id: "C10",
    topic: "Calculus (Definite Integral)",
    difficulty: 1250,
    problem: "Evaluate the definite integral of $f(x) = 3x^2 + 4x$ from $x=0$ to $x=2$. That is, find $\\int_0^2 (3x^2+4x)dx$.",
    answer: "16",
  },
  {
    id: "C11",
    topic: "Calculus (U-Substitution)",
    difficulty: 1550,
    problem: "Evaluate $\\int_0^1 x(x^2 + 1)^3 dx$.",
    answer: "3.75",
  },
  {
    id: "C12",
    topic: "Calculus (Integration by Parts)",
    difficulty: 1650,
    problem: "Evaluate $\\int_1^e x \\ln(x) dx$.",
    answer: "(e²+1)/4",
  },
  {
    id: "C13",
    topic: "Calculus (Improper Integral)",
    difficulty: 1900,
    problem: "Evaluate the improper integral $\\int_1^\\infty \\frac{1}{x^2} dx$.",
    answer: "1",
  },
  {
    id: "C14",
    topic: "Calculus (Trigonometric Substitution)",
    difficulty: 2100,
    problem: "Evaluate $\\int_0^2 \\sqrt{4 - x^2} dx$.",
    answer: "π",
  },
  {
    id: "C15",
    topic: "Calculus (Partial Fractions)",
    difficulty: 2200,
    problem: "Evaluate $\\int_0^1 \\frac{1}{x^2 + 3x + 2} dx$.",
    answer: "ln(4/3)",
  },
  {
    id: "C41",
    topic: "Calculus (Ratio Test for Convergence)",
    difficulty: 1750,
    problem: "Consider the series $\\sum_{n=1}^{\\infty} \\frac{n^2}{2^n}$. Let $L$ be the limit from the Ratio Test. What is the value of $L$?",
    answer: "0.5",
  },
  {
    id: "C42",
    topic: "Calculus (Interval of Convergence)",
    difficulty: 2300,
    problem: "Find the radius of convergence for the power series $\\sum_{n=1}^{\\infty} \\frac{(x-3)^n}{n \\cdot 4^n}$.",
    answer: "4",
  },
  {
    id: "C43",
    topic: "Calculus (Area Between Curves)",
    difficulty: 1650,
    problem: "Find the area of the region enclosed by the curves $y=x^2$ and $y=x$.",
    answer: "1/6",
  },
  {
    id: "C44",
    topic: "Calculus (L'Hôpital's Rule with Logs)",
    difficulty: 2050,
    problem: "Evaluate the limit $\\lim_{x \\to 0^+} x \\ln(x)$.",
    answer: "0",
  },
  {
    id: "C45",
    topic: "Calculus (Separable Differential Equation)",
    difficulty: 1800,
    problem: "Solve the differential equation $\\frac{dy}{dx} = 2xy$ with the initial condition $y(0) = 5$. Find the value of $y(1)$.",
    answer: "5e",
  },
  {
    id: "C46",
    topic: "Calculus (Area in Polar Coordinates)",
    difficulty: 2150,
    problem: "Find the area of one petal of the rose curve $r = 4\\cos(2\\theta)$.",
    answer: "2π",
  },
  {
    id: "C63",
    topic: "Calculus (Indefinite Integral)",
    difficulty: 1100,
    problem: "Find the general antiderivative of $f(x) = 4x^3 + \\sec^2(x)$. The answer should not include the constant of integration, C.",
    answer: "x⁴ + tan(x)",
  },
  {
    id: "C64",
    topic: "Calculus (Fundamental Theorem of Calculus Part 1)",
    difficulty: 1700,
    problem: "Let $F(x) = \\int_2^x \\sqrt{t^3+1} \\, dt$. Find $F'(2)$.",
    answer: "3",
  },
  {
    id: "C65",
    topic: "Calculus (Integration by Parts - Tabular)",
    difficulty: 1800,
    problem: "Evaluate $\\int_0^1 x^2 e^x dx$.",
    answer: "e-2",
  },
  {
    id: "C66",
    topic: "Calculus (Trigonometric Integral)",
    difficulty: 1950,
    problem: "Evaluate $\\int_0^{\\pi/2} \\sin^2(x) dx$.",
    answer: "π/4",
  },
  {
    id: "C67",
    topic: "Calculus (Partial Fractions - Repeated Root)",
    difficulty: 2350,
    problem: "When decomposing $\\frac{x}{(x-1)^2}$ into partial fractions, one term is $\\frac{A}{x-1}$ and the other is $\\frac{B}{(x-1)^2}$. What is the value of A?",
    answer: "1",
  },
  {
    id: "C68",
    topic: "Calculus (p-Series Convergence)",
    difficulty: 1500,
    problem: "For what values of $p$ does the series $\\sum_{n=1}^{\\infty} \\frac{1}{n^{3p-2}}$ converge? Express your answer as an inequality for p.",
    answer: "p > 1",
  },
  {
    id: "C69",
    topic: "Calculus (Alternating Series Error Bound)",
    difficulty: 2100,
    problem: "The alternating series $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}}{n^2}$ is approximated by its first 3 terms. What is the maximum absolute error in this approximation, according to the Alternating Series Estimation Theorem?",
    answer: "1/16",
  },
  {
    id: "C70",
    topic: "Calculus (Integral Test)",
    difficulty: 1850,
    problem: "Use the integral test to determine if $\\sum_{n=1}^{\\infty} \\frac{\\ln(n)}{n}$ converges or diverges. If the corresponding improper integral diverges, the answer is 'diverges'. If it converges to a value L, the answer is L.",
    answer: "diverges",
  },
  {
    id: "C71",
    topic: "Calculus (Maclaurin Series for sin(x))",
    difficulty: 1900,
    problem: "Find the coefficient of the $x^5$ term in the Maclaurin series for $f(x) = \\sin(x)$.",
    answer: "1/120",
  },
  {
    id: "C72",
    topic: "Calculus (Taylor Series for ln(x))",
    difficulty: 2150,
    problem: "Find the third-degree Taylor polynomial for $f(x) = \\ln(x)$ centered at $a=1$. What is the coefficient of the $(x-1)^3$ term?",
    answer: "1/3",
  },
  {
    id: "C73",
    topic: "Calculus (Volume of Revolution - Washer Method)",
    difficulty: 1950,
    problem: "Find the volume of the solid obtained by rotating the region bounded by $y=x$ and $y=\\sqrt{x}$ about the x-axis.",
    answer: "π/6",
  },
  {
    id: "C74",
    topic: "Calculus (Arc Length - Polar)",
    difficulty: 2400,
    problem: "Find the arc length of the cardioid $r = 1 + \\cos(\\theta)$.",
    answer: "8",
  },
  {
    id: "C75",
    topic: "Calculus (Surface Area of Revolution)",
    difficulty: 2300,
    problem: "Find the surface area of the solid generated by revolving the curve $y = x^3$ from $x=0$ to $x=1$ about the x-axis. The integral setup is $\\int_0^1 2\\pi x^3 \\sqrt{1+(3x^2)^2} dx$. What is the final value?",
    answer: "π/27 * (10√10 - 1)",
  },
  {
    id: "C76",
    topic: "Calculus (Work - Pumping Water)",
    difficulty: 2250,
    problem: "A conical tank with its vertex down has a height of 10m and a radius of 5m. It is filled with water to a height of 8m. How much work (in Joules) is required to pump all the water out over the top? Use density of water $\\rho=1000$ kg/m³ and $g=9.8$ m/s². The answer is a multiple of $\\pi$. What is the numerical coefficient?",
    answer: "9800 * (10*8³/3 - 8⁴/4)",
  },
  {
    id: "C77",
    topic: "Calculus (Improper Integral - Discontinuity)",
    difficulty: 1950,
    problem: "Evaluate the improper integral $\\int_0^1 \\frac{1}{\\sqrt{x}} dx$.",
    answer: "2",
  },
  {
    id: "C78",
    topic: "Calculus (Radius of Convergence)",
    difficulty: 2200,
    problem: "Find the radius of convergence of the power series $\\sum_{n=0}^{\\infty} \\frac{n! x^n}{n^n}$.",
    answer: "e",
  },
{
  id: "C117",
  topic: "Calculus (Definite Integral)",
  difficulty: 1200,
  problem: "Evaluate $\\int_1^2 (4x^3 - 2x) dx$.",
  answer: "12",
},
{
  id: "C118",
  topic: "Calculus (U-Substitution)",
  difficulty: 1500,
  problem: "Evaluate $\\int_0^{\\pi/2} \\cos(x) \\sin(\\sin(x)) dx$.",
  answer: "1-cos(1)",
},
{
  id: "C119",
  topic: "Calculus (Integral of exponential)",
  difficulty: 1300,
  problem: "Evaluate $\\int_0^{\\ln(2)} e^{3x} dx$.",
  answer: "7/3",
},
{
  id: "C120",
  topic: "Calculus (Area Between Curves)",
  difficulty: 1700,
  problem: "Find the area of the region bounded by $y=8-x^2$ and $y=x^2$.",
  answer: "128/3",
},
{
  id: "C121",
  topic: "Calculus (Volume of Revolution - Disk)",
  difficulty: 1750,
  problem: "The region under the curve $y=e^x$ from $x=0$ to $x=1$ is rotated about the x-axis. Find the volume.",
  answer: "π(e²-1)/2",
},
{
  id: "C122",
  topic: "Calculus (Integration by Parts)",
  difficulty: 1800,
  problem: "Evaluate $\\int_0^{\\pi} x \\sin(x) dx$.",
  answer: "π",
},
{
  id: "C123",
  topic: "Calculus (Trigonometric Integral)",
  difficulty: 1900,
  problem: "Evaluate $\\int_0^{\\pi/4} \\tan^2(x) dx$.",
  answer: "1 - π/4",
},
{
  id: "C124",
  topic: "Calculus (Trigonometric Substitution)",
  difficulty: 2150,
  problem: "Evaluate $\\int_0^1 \\frac{1}{1+x^2} dx$.",
  answer: "π/4",
},
{
  id: "C125",
  topic: "Calculus (Partial Fractions)",
  difficulty: 2250,
  problem: "Evaluate $\\int_2^3 \\frac{3x-1}{x^2-x} dx$.",
  answer: "ln(9)",
},
{
  id: "C126",
  topic: "Calculus (Improper Integral)",
  difficulty: 1950,
  problem: "Evaluate $\\int_0^\\infty e^{-2x} dx$.",
  answer: "0.5",
},
{
  id: "C127",
  topic: "Calculus (Comparison Test for Integrals)",
  difficulty: 2050,
  problem: "Does the integral $\\int_1^\\infty \\frac{1}{x + e^x} dx$ converge or diverge? (Answer 'converge' or 'diverge')",
  answer: "converge",
},
{
  id: "C128",
  topic: "Calculus (Arc Length)",
  difficulty: 2300,
  problem: "Find the arc length of the curve $y = \\ln(\\cos(x))$ from $x=0$ to $x=\\pi/4$.",
  answer: "ln(√2 + 1)",
},
{
  id: "C129",
  topic: "Calculus (Volume of Revolution - Shell Method)",
  difficulty: 2200,
  problem: "Use the shell method to find the volume generated by revolving the region bounded by $y=x^2$, $y=0$, and $x=2$ about the y-axis.",
  answer: "8π",
},
{
  id: "C130",
  topic: "Calculus (Work)",
  difficulty: 2100,
  problem: "A force of $10$ N is required to hold a spring stretched $0.2$ m beyond its natural length. How much work (in Joules) is done in stretching it from its natural length to $0.5$ m beyond its natural length? ($F=kx$)",
  answer: "6.25",
},
{
  id: "C131",
  topic: "Calculus (Geometric Series)",
  difficulty: 1650,
  problem: "Find the sum of the series $\\sum_{n=1}^{\\infty} 5(\\frac{1}{2})^{n-1}$.",
  answer: "10",
},
{
  id: "C132",
  topic: "Calculus (Ratio Test)",
  difficulty: 1850,
  problem: "For what values of x does the series $\\sum_{n=1}^{\\infty} \\frac{x^n}{n!}$ converge? (Answer in interval notation)",
  answer: "(-∞, ∞)",
},
{
  id: "C133",
  topic: "Calculus (Taylor Series Coefficient)",
  difficulty: 2350,
  problem: "Find the coefficient of the $(x-\\pi/2)^2$ term in the Taylor series expansion of $f(x)=\\cos(x)$ centered at $a=\\pi/2$.",
  answer: "-0.5",
},
{
  id: "C134",
  topic: "Calculus (Alternating Series)",
  difficulty: 1750,
  problem: "Does the series $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{\\sqrt{n}}$ converge absolutely, converge conditionally, or diverge?",
  answer: "converge conditionally",
},
{
  id: "C135",
  topic: "Calculus (Power Series from Geometric)",
  difficulty: 2000,
  problem: "Find a power series representation for $f(x) = \\frac{1}{1+x^2}$. What is the coefficient of the $x^4$ term?",
  answer: "1",
},
{
  id: "C136",
  topic: "Calculus (Integration by Parts - Cyclic)",
  difficulty: 2450,
  problem: "Evaluate $\\int_0^{\\pi/2} e^x \\cos(x) dx$.",
  answer: "(e^(π/2) - 1)/2",
},



  // --- Calculus III & Advanced Topics ---



  {
    id: "C20",
    topic: "Calculus (Partial Derivative)",
    difficulty: 1700,
    problem: "Let $f(x, y) = x^3y^2 - 2xy + 5y$. Find the value of the partial derivative $\\frac{\\partial f}{\\partial x}$ at the point $(2, 3)$.",
    answer: "102",
  },
  {
    id: "C21",
    topic: "Calculus (Gradient)",
    difficulty: 1800,
    problem: "Let $f(x, y) = x^2 + y^2$. Find the magnitude of the gradient vector, $|\\nabla f|$, at the point $(3, 4)$.",
    answer: "10",
  },
  {
    id: "C22",
    topic: "Calculus (Directional Derivative)",
    difficulty: 1950,
    problem: "Find the directional derivative of $f(x, y) = e^{xy}$ at the point $(1, 2)$ in the direction of the vector $v = \\langle 3, 4 \\rangle$.",
    answer: "(11/5)*e²",
  },
  {
    id: "C23",
    topic: "Calculus (Double Integral)",
    difficulty: 2050,
    problem: "Evaluate the double integral of $f(x, y) = 6xy$ over the rectangular region $R$ where $0 \\le x \\le 2$ and $0 \\le y \\le 1$.",
    answer: "6",
  },
  {
    id: "C24",
    topic: "Calculus (Triple Integral)",
    difficulty: 2400,
    problem: "Use a triple integral in spherical coordinates to find the volume of a sphere with radius $R=3$.",
    answer: "36π",
  },
  {
    id: "C25",
    topic: "Calculus (Line Integral)",
    difficulty: 2300,
    problem: "Evaluate the line integral $\\int_C (x+y) ds$ where $C$ is the line segment from $(0,0)$ to $(1,2)$.",
    answer: "3√5 / 2",
  },
  {
    id: "C26",
    topic: "Calculus (Line Integral)",
    difficulty: 2500,
    problem: "Let $F(x,y) = \\langle y, -x \\rangle$. Calculate the work done ($\\int_C F \\cdot dr$) along the path $C$, the top half of the unit circle $x^2+y^2=1$ from $(1,0)$ to $(-1,0)$.",
    answer: "-π",
  },
  {
    id: "C27",
    topic: "Calculus (Curl of a Vector Field)",
    difficulty: 2600,
    problem: "Let the vector field $F = \\langle yz, xz, xy \\rangle$. Find the magnitude of the curl of $F$, $|\\nabla \\times F|$, at the point $(1, 2, 3)$.",
    answer: "0",
  },
  {
    id: "C28",
    topic: "Calculus (Divergence)",
    difficulty: 2550,
    problem: "Let the vector field $F = \\langle x^3, y^3z, x^2y \\rangle$. Find the divergence of $F$, $\\nabla \\cdot F$, at the point $(2, 1, -1)$.",
    answer: "9",
  },
  {
    id: "C29",
    topic: "Calculus (Green's Theorem)",
    difficulty: 2700,
    problem: "Use Green's Theorem to evaluate the line integral $\\oint_C (y^2 dx + 3xy dy)$ where $C$ is the boundary of the square with vertices $(0,0), (1,0), (1,1),$ and $(0,1)$, traversed counter-clockwise.",
    answer: "0.5",
  },
  {
    id: "C30",
    topic: "Calculus (Stokes' Theorem)",
    difficulty: 2950,
    problem: "Let $F = \\langle y, z, x \\rangle$. Let $S$ be the surface of the plane $2x + y + 2z = 2$ in the first octant. What is the value of the surface integral $\\iint_S (\\nabla \\times F) \\cdot dS$?",
    answer: "-1.5",
  },
  {
    id: "C31",
    topic: "Calculus (Geometric Series)",
    difficulty: 1700,
    problem: "What is the sum of the infinite geometric series $\\sum_{n=0}^{\\infty} (\\frac{2}{3})^n$?",
    answer: "3",
  },
  {
    id: "C32",
    topic: "Calculus (Taylor Series)",
    difficulty: 2000,
    problem: "Let $f(x) = e^x$. Find the coefficient of the $x^3$ term in the Maclaurin series expansion of $f(x)$.",
    answer: "1/6",
  },
  {
    id: "C33",
    topic: "Calculus (L'Hôpital's Rule)",
    difficulty: 1900,
    problem: "Evaluate the limit $\\lim_{x \\to 0} \\frac{\\sin(x) - x}{x^3}$.",
    answer: "-1/6",
  },
  {
    id: "C34",
    topic: "Calculus (Volume of Revolution)",
    difficulty: 1800,
    problem: "Find the volume of the solid generated by revolving the region bounded by $y = \\sqrt{x}$, $y = 0$, and $x = 4$ about the x-axis.",
    answer: "8π",
  },
  {
    id: "C35",
    topic: "Calculus (Arc Length)",
    difficulty: 2250,
    problem: "Find the arc length of the curve $y = \\frac{2}{3}x^{3/2}$ from $x=0$ to $x=3$.",
    answer: "14/3",
  },
  {
    id: "C47",
    topic: "Calculus (Divergence Theorem)",
    difficulty: 3000,
    problem: "Let $F = \\langle x^3, y^3, z^3 \\rangle$. Use the Divergence Theorem to calculate the flux of F across the surface of the unit sphere $x^2+y^2+z^2=1$.",
    answer: "12π/5",
  },
  {
    id: "C48",
    topic: "Calculus (Jacobian of Transformation)",
    difficulty: 2450,
    problem: "Consider the change of variables from $(x, y)$ to $(u, v)$ where $x = u^2 - v^2$ and $y = 2uv$. What is the absolute value of the Jacobian determinant, $|\\frac{\\partial(x,y)}{\\partial(u,v)}|$?",
    answer: "4(u²+v²)",
  },
  {
    id: "C49",
    topic: "Calculus (Surface Integral of a Scalar Function)",
    difficulty: 2650,
    problem: "Evaluate the surface integral $\\iint_S z \\,dS$ where $S$ is the part of the plane $x+y+z=1$ that lies in the first octant.",
    answer: "√3 / 6",
  },
  {
    id: "C50",
    topic: "Calculus (Center of Mass)",
    difficulty: 2350,
    problem: "A thin rod lies on the x-axis from $x=0$ to $x=2$. Its density is given by $\\rho(x) = x^2$. Find the x-coordinate of the center of mass.",
    answer: "1.5",
  },
  {
    id: "C79",
    topic: "Calculus (Second Partial Derivatives - Clairaut's Theorem)",
    difficulty: 1850,
    problem: "Let $f(x, y) = x^3y^5 - 2x^2y^3$. Find the mixed partial derivative $f_{xy}(1, 1)$.",
    answer: "3",
  },
  {
    id: "C80",
    topic: "Calculus (Tangent Plane)",
    difficulty: 2100,
    problem: "Find the equation of the tangent plane to the surface $z = x^2 + y^2$ at the point $(1, 2, 5)$. The equation is $z-5 = A(x-1) + B(y-2)$. What is the value of $A+B$?",
    answer: "6",
  },
  {
    id: "C81",
    topic: "Calculus (Local Extrema - Second Derivative Test)",
    difficulty: 2450,
    problem: "The function $f(x, y) = x^3 - 3x + y^2$ has a critical point at $(1, 0)$. Is this point a local maximum, local minimum, or a saddle point?",
    answer: "local minimum",
  },
  {
    id: "C82",
    topic: "Calculus (Lagrange Multipliers)",
    difficulty: 2600,
    problem: "Use Lagrange multipliers to find the maximum value of the function $f(x, y) = xy$ subject to the constraint $x+y=10$.",
    answer: "25",
  },
  {
    id: "C83",
    topic: "Calculus (Double Integral - Polar)",
    difficulty: 2150,
    problem: "Evaluate the double integral of $f(x,y) = e^{-(x^2+y^2)}$ over the disk $D$ with center the origin and radius 3.",
    answer: "π(1 - e⁻⁹)",
  },
  {
    id: "C84",
    topic: "Calculus (Double Integral - General Region)",
    difficulty: 2300,
    problem: "Evaluate $\\int_0^1 \\int_x^1 \\sin(y^2) dy dx$. (Hint: Change the order of integration).",
    answer: "(1-cos(1))/2",
  },
  {
    id: "C85",
    topic: "Calculus (Triple Integral - Cylindrical)",
    difficulty: 2500,
    problem: "Find the volume of the solid that lies within the cylinder $x^2+y^2=1$, below the plane $z=4$, and above the paraboloid $z=1-x^2-y^2$.",
    answer: "3.5π",
  },
  {
    id: "C86",
    topic: "Calculus (Line Integral of a Vector Field)",
    difficulty: 2400,
    problem: "Let $F = \\langle x, y \\rangle$. Evaluate the line integral $\\int_C F \\cdot dr$ where $C$ is the curve $r(t) = \\langle t^2, t^3 \\rangle$ for $0 \\le t \\le 1$.",
    answer: "1",
  },
  {
    id: "C87",
    topic: "Calculus (Fundamental Theorem for Line Integrals)",
    difficulty: 2350,
    problem: "Let $F = \\nabla f$ where $f(x, y) = x^2y$. Evaluate $\\int_C F \\cdot dr$ where C is any path from $(1, 2)$ to $(3, 4)$.",
    answer: "34",
  },
  {
    id: "C88",
    topic: "Calculus (Green's Theorem - Area)",
    difficulty: 2750,
    problem: "Use the formula $A = \\frac{1}{2} \\oint_C x dy - y dx$ to find the area of the ellipse $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$, parameterized by $x=a\\cos(t), y=b\\sin(t)$.",
    answer: "πab",
  },
  {
    id: "C89",
    topic: "Calculus (Curl of a Gradient)",
    difficulty: 2550,
    problem: "Let $f(x,y,z) = x^2 y^3 z^4$. Let $F = \\nabla f$. What is the curl of F, $\\nabla \\times F$?",
    answer: "0",
  },
  {
    id: "C90",
    topic: "Calculus (Divergence of a Curl)",
    difficulty: 2650,
    problem: "Let $F = \\langle x^2y, y^2z, z^2x \\rangle$. Let $G = \\nabla \\times F$. What is the divergence of G, $\\nabla \\cdot G$?",
    answer: "0",
  },
  {
    id: "C91",
    topic: "Calculus (Surface Integral of a Vector Field)",
    difficulty: 2850,
    problem: "Let $F = \\langle 0, 0, z \\rangle$. Let S be the top hemisphere of the sphere $x^2+y^2+z^2=1$ with upward orientation. Evaluate $\\iint_S F \\cdot dS$.",
    answer: "2π/3",
  },
  {
    id: "C92",
    topic: "Calculus (Stokes' Theorem - Simple)",
    difficulty: 2900,
    problem: "Let $F = \\langle -y, x, 0 \\rangle$. Let $C$ be the unit circle in the xy-plane, oriented counter-clockwise. Use Stokes' Theorem to evaluate $\\oint_C F \\cdot dr$.",
    answer: "2π",
  },
  {
    id: "C93",
    topic: "Calculus (Divergence Theorem - Simple)",
    difficulty: 2800,
    problem: "Let $F = \\langle x, y, z \\rangle$. Use the Divergence Theorem to calculate the flux of F across the surface of the cube with vertices at $(\\pm 1, \\pm 1, \\pm 1)$.",
    answer: "24",
  },
  {
    id: "C94",
    topic: "Calculus (Chain Rule - Multivariable)",
    difficulty: 2000,
    problem: "Let $z = x^2+y^2$, where $x=\\cos(t)$ and $y=\\sin(t)$. Find $\\frac{dz}{dt}$.",
    answer: "0",
  },
  {
    id: "C95",
    topic: "Calculus (Directional Derivative - Max Rate of Change)",
    difficulty: 1850,
    problem: "Find the maximum rate of change of $f(x,y) = \\sin(xy)$ at the point $(1, 0)$.",
    answer: "1",
  },
  {
    id: "C96",
    topic: "Calculus (Volume with Double Integrals)",
    difficulty: 2000,
    problem: "Find the volume of the solid under the plane $z=2x+y$ and above the rectangle $R = [0,1] \\times [0,2]$.",
    answer: "4",
  },
{
  id: "C137",
  topic: "Calculus (Partial Derivative)",
  difficulty: 1650,
  problem: "Let $f(x, y) = e^{xy^2}$. Find the partial derivative $\\frac{\\partial f}{\\partial y}$ at the point $(1, 2)$.",
  answer: "4e⁴",
},
{
  id: "C138",
  topic: "Calculus (Gradient)",
  difficulty: 1750,
  problem: "Let $f(x, y) = \\ln(x^2 + y^2)$. Find the gradient vector $\\nabla f$ at the point $(1, 1)$.",
  answer: "<1, 1>",
},
{
  id: "C139",
  topic: "Calculus (Double Integral)",
  difficulty: 2000,
  problem: "Evaluate $\\int_0^1 \\int_0^2 (x + y) dy dx$.",
  answer: "3",
},
{
  id: "C140",
  topic: "Calculus (Vector Operations)",
  difficulty: 1250,
  problem: "Let $u = \\langle 1, -2, 3 \\rangle$ and $v = \\langle 3, 0, 5 \\rangle$. Find $2u - v$.",
  answer: "<-1, -4, 1>",
},
{
  id: "C141",
  topic: "Calculus (Cross Product)",
  difficulty: 1550,
  problem: "Find the cross product $i \\times (i+j)$.",
  answer: "k",
},
{
  id: "C142",
  topic: "Calculus (Directional Derivative)",
  difficulty: 1950,
  problem: "Find the directional derivative of $f(x, y) = x^2y^3$ at the point $(2,1)$ in the direction of the vector $v = \\langle 1, 1 \\rangle$.",
  answer: "8√2",
},
{
  id: "C143",
  topic: "Calculus (Tangent Plane)",
  difficulty: 2150,
  problem: "Find the z-intercept of the tangent plane to the surface $z = 3x^2 - y^2 + 2$ at the point $(1, 2, 1)$.",
  answer: "-1",
},
{
  id: "C144",
  topic: "Calculus (Local Extrema)",
  difficulty: 2400,
  problem: "The function $f(x, y) = xy - x^2 - y^2 - 2x - 2y + 4$ has one critical point. What is the y-coordinate of this point?",
  answer: "-2",
},
{
  id: "C145",
  topic: "Calculus (Double Integral - Polar)",
  difficulty: 2200,
  problem: "Use polar coordinates to find the volume of the solid under the paraboloid $z = x^2+y^2$ and above the disk $x^2+y^2 \\le 9$.",
  answer: "81π/2",
},
{
  id: "C146",
  topic: "Calculus (Triple Integral)",
  difficulty: 2350,
  problem: "Evaluate the triple integral of $f(x,y,z) = xyz$ over the cube defined by $0 \\le x \\le 1$, $0 \\le y \\le 2$, and $0 \\le z \\le 3$.",
  answer: "4.5",
},
{
  id: "C147",
  topic: "Calculus (Line Integral - Scalar)",
  difficulty: 2250,
  problem: "Evaluate $\\int_C x ds$ where C is the line segment from $(1,2)$ to $(4,6)$.",
  answer: "12.5",
},
{
  id: "C148",
  topic: "Calculus (Line Integral - Vector Field)",
  difficulty: 2450,
  problem: "Evaluate $\\int_C F \\cdot dr$ where $F(x,y) = \\langle y, x \\rangle$ and C is the path $r(t) = \\langle \\cos(t), \\sin(t) \\rangle$ for $0 \\le t \\le \\pi$.",
  answer: "0",
},
{
  id: "C149",
  topic: "Calculus (Conservative Vector Fields)",
  difficulty: 2300,
  problem: "The vector field $F = \\langle 2xy, x^2 \\rangle$ is conservative. Find a potential function $f(x,y)$ such that $\\nabla f = F$ and $f(0,0)=0$. Evaluate $f(2,3)$.",
  answer: "12",
},
{
  id: "C150",
  topic: "Calculus (Green's Theorem)",
  difficulty: 2750,
  problem: "Use Green's Theorem to evaluate $\\oint_C (x^2y dx + x dy)$ where C is the circle $x^2+y^2=4$ oriented counter-clockwise.",
  answer: "-4π",
},
{
  id: "C151",
  topic: "Calculus (Curl and Divergence)",
  difficulty: 2500,
  problem: "Let $F = \\langle x^2, y^2, z^2 \\rangle$. Find the divergence of the curl of F, $\\nabla \\cdot (\\nabla \\times F)$.",
  answer: "0",
},
{
  id: "C152",
  topic: "Calculus (Surface Integral)",
  difficulty: 2850,
  problem: "Evaluate the surface integral $\\iint_S z^2 dS$ where $S$ is the sphere $x^2+y^2+z^2=1$.",
  answer: "4π/3",
},
{
  id: "C153",
  topic: "Calculus (Stokes' Theorem)",
  difficulty: 2900,
  problem: "Let $F = \\langle 2y, 3z, x \\rangle$ and $S$ be the part of the paraboloid $z=4-x^2-y^2$ above the xy-plane. Evaluate $\\iint_S (\\nabla \\times F) \\cdot dS$.",
  answer: "-8π",
},
{
  id: "C154",
  topic: "Calculus (Divergence Theorem)",
  difficulty: 2950,
  problem: "Let $F = \\langle x, 2y, 3z \\rangle$. Use the Divergence Theorem to find the flux of F across the surface of the box bounded by $0 \\le x \\le 1, 0 \\le y \\le 1, 0 \\le z \\le 1$.",
  answer: "6",
},
{
  id: "C155",
  topic: "Calculus (Cylindrical Coordinates)",
  difficulty: 2400,
  problem: "The point $(x,y,z) = (3, 4, 5)$ is expressed in cylindrical coordinates as $(r, \\theta, z)$. What is the value of r?",
  answer: "5",
},
{
  id: "C156",
  topic: "Calculus (Spherical Coordinates)",
  difficulty: 2600,
  problem: "A point has spherical coordinates $(\\rho, \\theta, \\phi) = (4, \\pi/4, \\pi/2)$. What is its x-coordinate in Cartesian coordinates?",
  answer: "2√2",
},



  // --- Linear Algebra: Basic Operations ---



  {
    id: "LA01",
    topic: "Linear Algebra (Matrix Multiplication)",
    difficulty: 1200,
    problem: "Let MATRIX(A = [[1, 2], [3, 4]]) and MATRIX(B = [[2, 0], [1, 3]]). Find the element in the first row, first column of the product $AB$.",
    answer: "4",
  },
  {
    id: "LA02",
    topic: "Linear Algebra (Matrix Transpose)",
    difficulty: 1150,
    problem: "Let MATRIX(C = [[1, 2, 3], [4, 5, 6]]). Find the element in the second row, first column of the transpose $C^T$.",
    answer: "2",
  },
  {
    id: "LA03",
    topic: "Linear Algebra (Dot Product)",
    difficulty: 1050,
    problem: "Find the dot product of the vectors $u = \\langle 2, -3, 5 \\rangle$ and $v = \\langle 1, 4, -2 \\rangle$.",
    answer: "-20",
  },
  {
    id: "LA04",
    topic: "Linear Algebra (Determinant 2x2)",
    difficulty: 1300,
    problem: "Find the determinant of the matrix MATRIX(A = [[-5, 3], [2, 1]]).",
    answer: "-11",
  },
  {
    id: "LA05",
    topic: "Linear Algebra (Determinant 3x3)",
    difficulty: 1750,
    problem: "Find the determinant of the matrix MATRIX(A = [[1, 2, 3], [0, 4, 5], [1, 0, 6]]).",
    answer: "22",
  },
  {
    id: "LA06",
    topic: "Linear Algebra (Matrix Inverse 2x2)",
    difficulty: 1650,
    problem: "Let MATRIX(A = [[4, 7], [2, 3]]). Find the element in the second row, second column of the inverse matrix $A^{-1}$.",
    answer: "-2",
  },
    {
    id: "LA20",
    topic: "Linear Algebra (Cross Product)",
    difficulty: 1500,
    problem: "Find the magnitude of the cross product of the vectors $u = \\langle 1, 2, 3 \\rangle$ and $v = \\langle 4, 5, 6 \\rangle$.",
    answer: "3√6",
  },
  {
    id: "LA21",
    topic: "Linear Algebra (Area of Parallelogram)",
    difficulty: 1600,
    problem: "Find the area of the parallelogram with adjacent sides given by the vectors $u = \\langle 3, 1, 0 \\rangle$ and $v = \\langle 1, 4, 0 \\rangle$.",
    answer: "11",
  },
  {
    id: "LA22",
    topic: "Linear Algebra (Subspace Check)",
    difficulty: 1900,
    problem: "Consider the set of all vectors $\\langle x, y, z \\rangle$ in $\\mathbb{R}^3$ such that $x+y-z=0$. This forms a subspace. What is the dimension of this subspace?",
    answer: "2",
  },
  {
    id: "LA23",
    topic: "Linear Algebra (Column Space)",
    difficulty: 2100,
    problem: "Find the dimension of the column space (the rank) of the matrix MATRIX(A = [[1, 0, 2], [-1, 1, 0], [0, 1, 2]]).",
    answer: "2",
  },
  {
    id: "LA24",
    topic: "Linear Algebra (Kernel of a Transformation)",
    difficulty: 2050,
    problem: "Let $T: \\mathbb{R}^3 \\to \\mathbb{R}^2$ be a linear transformation defined by the matrix MATRIX(A = [[1, 2, 3], [2, 4, 6]]). Find the dimension of the kernel (null space) of T.",
    answer: "2",
  },
  {
    id: "LA32",
    topic: "Linear Algebra (Solving Systems)",
    difficulty: 1350,
    problem: "Solve the system of equations: $x + 2y = 7$ and $3x - y = 0$. What is the value of $y$?",
    answer: "3",
  },
  {
    id: "LA33",
    topic: "Linear Algebra (Linear Combination)",
    difficulty: 1450,
    problem: "Express the vector $w = \\langle 7, 7 \\rangle$ as a linear combination of $u = \\langle 1, 2 \\rangle$ and $v = \\langle 3, 1 \\rangle$. If $w = c_1u + c_2v$, what is the value of $c_1$?",
    answer: "2",
  },
  {
    id: "LA34",
    topic: "Linear Algebra (Properties of Transpose)",
    difficulty: 1550,
    problem: "Let MATRIX(A = [[1, 2], [3, 4]]) and MATRIX(B = [[0, 1], [1, 0]]). Find the element in the second row, first column of $(AB)^T$.",
    answer: "4",
  },
{
  id: "LA57",
  topic: "Linear Algebra (Matrix Addition)",
  difficulty: 1050,
  problem: "Let MATRIX(A = [[1, 5], [-2, 3]]) and MATRIX(B = [[0, -1], [4, -1]]). Find $A+B$. What is the element in the second row, first column?",
  answer: "2",
},
{
  id: "LA58",
  topic: "Linear Algebra (Scalar Multiplication)",
  difficulty: 1100,
  problem: "Let MATRIX(A = [[1, 2, 3], [4, 5, 6]]). Find the element in the second row, third column of $3A$.",
  answer: "18",
},
{
  id: "LA59",
  topic: "Linear Algebra (Matrix-Vector Product)",
  difficulty: 1200,
  problem: "Let MATRIX(A = [[1, 2], [3, 4]]) and vector $v = \\langle 5, -1 \\rangle$. Find the first component of the vector $Av$.",
  answer: "3",
},
{
  id: "LA60",
  topic: "Linear Algebra (Trace of a Matrix)",
  difficulty: 1150,
  problem: "Find the trace of the matrix MATRIX(A = [[5, 2, 8], [1, -3, 0], [4, 9, 1]]).",
  answer: "3",
},
{
  id: "LA61",
  topic: "Linear Algebra (Matrix Multiplication)",
  difficulty: 1300,
  problem: "Let MATRIX(A = [[1, 0], [2, 1]]) and MATRIX(B = [[4, 1], [3, 2]]). Find the product $AB$. What is the entry in the second row, second column?",
  answer: "4",
},
{
  id: "LA62",
  topic: "Linear Algebra (Determinant 3x3)",
  difficulty: 1700,
  problem: "Find the determinant of the matrix MATRIX(A = [[1, 0, 2], [-1, 3, 0], [0, 2, 1]]).",
  answer: "-5",
},
{
  id: "LA63",
  topic: "Linear Algebra (Matrix Inverse 2x2)",
  difficulty: 1600,
  problem: "Let MATRIX(A = [[1, 2], [1, 3]]). Find the element in the first row, first column of $A^{-1}$.",
  answer: "3",
},
{
  id: "LA64",
  topic: "Linear Algebra (Solving Systems with Inverse)",
  difficulty: 1800,
  problem: "The solution to $Ax=b$ is $x=A^{-1}b$. Given MATRIX(A⁻¹ = [[3, -2], [-1, 1]]) and $b = \\langle 1, 2 \\rangle$, find the first component of the solution vector $x$.",
  answer: "-1",
},
{
  id: "LA65",
  topic: "Linear Algebra (Properties of Transpose)",
  difficulty: 1400,
  problem: "Let $A$ and $B$ be $2 \\times 2$ matrices. If the element in the first row, second column of $A$ is 5, what is the element in the second row, first column of $A^T$?",
  answer: "5",
},
{
  id: "LA66",
  topic: "Linear Algebra (Symmetric Matrix)",
  difficulty: 1250,
  problem: "For what value of $k$ is the matrix MATRIX(A = [[2, 7], [k, 5]]) symmetric?",
  answer: "7",
},
{
  id: "LA67",
  topic: "Linear Algebra (Skew-Symmetric Matrix)",
  difficulty: 1500,
  problem: "For what value of $k$ is the matrix MATRIX(A = [[0, -3], [3, k]]) skew-symmetric?",
  answer: "0",
},
{
  id: "LA68",
  topic: "Linear Algebra (System of Equations)",
  difficulty: 1350,
  problem: "Find the value of $z$ for the system: $x+y+z=6$, $x-y=0$, $y+z=5$.",
  answer: "3",
},
{
  id: "LA69",
  topic: "Linear Algebra (Augmented Matrix)",
  difficulty: 1450,
  problem: "A system of equations is represented by the augmented matrix MATRIX([[1, 2 | 5], [0, 1 | 2]]). What is the value of $x$?",
  answer: "1",
},
{
  id: "LA70",
  topic: "Linear Algebra (Properties of Determinants)",
  difficulty: 1900,
  problem: "If $A$ is a $3 \\times 3$ matrix with $\\det(A)=2$, what is $\\det(3A)$?",
  answer: "54",
},
{
  id: "LA71",
  topic: "Linear Algebra (Determinant of Product)",
  difficulty: 1850,
  problem: "If $A$ and $B$ are $2 \\times 2$ matrices with $\\det(A)=4$ and $\\det(B)=-3$, what is $\\det(AB)$?",
  answer: "-12",
},
{
  id: "LA72",
  topic: "Linear Algebra (Inverse of Product)",
  difficulty: 2000,
  problem: "Let $A, B$ be invertible matrices. The expression $(AB)^{-1}$ is equivalent to which of the following: $A^{-1}B^{-1}$, $B^{-1}A^{-1}$, or $A B$?",
  answer: "B⁻¹A⁻¹",
},
{
  id: "LA73",
  topic: "Linear Algebra (Elementary Matrices)",
  difficulty: 2200,
  problem: "Let $E$ be the $2 \\times 2$ elementary matrix that swaps two rows. What is the determinant of $E$?",
  answer: "-1",
},
{
  id: "LA74",
  topic: "Linear Algebra (LU Decomposition)",
  difficulty: 2400,
  problem: "Let MATRIX(A = [[2, 1], [4, 5]]). In the LU decomposition $A=LU$, where L is lower triangular with 1s on the diagonal, what is the entry in the second row, first column of L?",
  answer: "2",
},
{
  id: "LA75",
  topic: "Linear Algebra (Adjugate Matrix)",
  difficulty: 2300,
  problem: "For MATRIX(A = [[a, b], [c, d]]), the adjugate matrix is MATRIX([[d, -b], [-c, a]]). If $A^{-1} = \\frac{1}{\\det(A)} \\text{adj}(A)$, what is the element in the first row, second column of the inverse of MATRIX([[1, 2], [3, 4]])?",
  answer: "1",
},
{
  id: "LA76",
  topic: "Linear Algebra (Powers of a Diagonal Matrix)",
  difficulty: 1650,
  problem: "Let MATRIX(D = [[2, 0], [0, 3]]). Find the element in the second row, second column of $D^3$.",
  answer: "27",
},



  // --- Linear Algebra: Vector Spaces & Eigenvalues ---



  {
    id: "LA10",
    topic: "Linear Algebra (Linear Independence)",
    difficulty: 1800,
    problem: "Consider the vectors $v_1=\\langle 1,0,1 \\rangle$, $v_2=\\langle 0,1,1 \\rangle$, and $v_3=\\langle 1,1,k \\rangle$. For what value of $k$ are these three vectors linearly dependent?",
    answer: "2",
  },
  {
    id: "LA11",
    topic: "Linear Algebra (Eigenvalues 2x2)",
    difficulty: 1900,
    problem: "Find the largest eigenvalue of the matrix MATRIX(A = [[2, 7], [1, 8]]).",
    answer: "9",
  },
  {
    id: "LA12",
    topic: "Linear Algebra (Eigenvalues 3x3)",
    difficulty: 2250,
    problem: "The matrix MATRIX(A = [[2, 0, 0], [1, 2, 1], [-1, 0, 1]]) is triangular. What is the sum of its eigenvalues?",
    answer: "5",
  },
  {
    id: "LA13",
    topic: "Linear Algebra (Eigenvector)",
    difficulty: 2150,
    problem: "The matrix MATRIX(A = [[3, 1], [1, 3]]) has an eigenvalue of $\\lambda=4$. An eigenvector corresponding to this eigenvalue is $\\langle k, 1 \\rangle$. What is the value of $k$?",
    answer: "1",
  },
  {
    id: "LA14",
    topic: "Linear Algebra (Diagonalization)",
    difficulty: 2650,
    problem: "Let MATRIX(A = [[1, 2], [0, 3]]). $A$ is diagonalizable as $A = PDP^{-1}$, where $D$ is a diagonal matrix of eigenvalues. What is the value in the second row, second column of $D$? (Assume eigenvalues are ordered from smallest to largest).",
    answer: "3",
  },
  {
    id: "LA15",
    topic: "Linear Algebra (Orthogonality)",
    difficulty: 1950,
    problem: "For what value of 'c' are the vectors $u = \\langle 2, c, -4 \\rangle$ and $v = \\langle 3, -1, 1 \\rangle$ orthogonal?",
    answer: "2",
  },
  {
    id: "LA16",
    topic: "Linear Algebra (Projection)",
    difficulty: 2350,
    problem: "Find the magnitude of the projection of vector $u = \\langle 1, 2, 2 \\rangle$ onto vector $v = \\langle 1, 1, 1 \\rangle$.",
    answer: "5/√3",
  },
  {
    id: "LA17",
    topic: "Linear Algebra (System of ODEs)",
    difficulty: 2800,
    problem: "Consider the system of linear differential equations $x' = Ax$ where MATRIX(A = [[0, 1], [-10, -7]]). What is the real part of the eigenvalue with the larger imaginary part?",
    answer: "-3.5",
  },
  {
    id: "LA18",
    topic: "Linear Algebra (Change of Basis)",
    difficulty: 2750,
    problem: "In $\\mathbb{R}^2$, let $B = \\{ \\langle 1,1 \\rangle, \\langle 0,2 \\rangle \\}$ be a basis. What is the determinant of the change-of-basis matrix from $B$ to the standard basis?",
    answer: "2",
  },
  {
    id: "LA19",
    topic: "Linear Algebra (Rank)",
    difficulty: 2000,
    problem: "What is the rank of the matrix MATRIX(A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]])?",
    answer: "2",
  },
  {
    id: "LA25",
    topic: "Linear Algebra (Matrix of a Linear Transformation)",
    difficulty: 2200,
    problem: "Let $T: \\mathbb{R}^2 \\to \\mathbb{R}^2$ be a linear transformation that rotates points counterclockwise by 90 degrees. What is the element in the first row, second column of the standard matrix for $T$?",
    answer: "-1",
  },
  {
    id: "LA26",
    topic: "Linear Algebra (Properties of Determinants)",
    difficulty: 1850,
    problem: "Let $A$ and $B$ be $3 \\times 3$ matrices with $\\det(A) = 4$ and $\\det(B) = -2$. What is the value of $\\det(2A B^{-1})$?",
    answer: "-16",
  },
  {
    id: "LA27",
    topic: "Linear Algebra (Gram-Schmidt Process)",
    difficulty: 2400,
    problem: "Let $v_1 = \\langle 3, 4 \\rangle$ and $v_2 = \\langle 1, 2 \\rangle$. Apply the Gram-Schmidt process to find an orthogonal basis $\{u_1, u_2\}$, where $u_1=v_1$. What is the first component of the resulting vector $u_2$?",
    answer: "-0.44",
  },
  {
    id: "LA28",
    topic: "Linear Algebra (Least Squares)",
    difficulty: 2500,
    problem: "Find the least squares solution $\\hat{x}$ to the inconsistent system $Ax=b$ where MATRIX(A = [[1, 1], [1, 2], [1, 3]]) and $b = \\langle 0, 1, 6 \\rangle$. What is the second component of the solution vector $\\hat{x}$?",
    answer: "3",
  },
  {
    id: "LA29",
    topic: "Linear Algebra (Eigenvalues of Symmetric Matrix)",
    difficulty: 2000,
    problem: "A $2 \\times 2$ symmetric matrix has a trace of 8 and a determinant of 12. What is its smallest eigenvalue?",
    answer: "2",
  },
  {
    id: "LA30",
    topic: "Linear Algebra (Orthogonal Matrix)",
    difficulty: 2300,
    problem: "For what positive value of 'a' is the matrix MATRIX(Q = [[a, -a], [a, a]]) orthogonal?",
    answer: "1/√2",
  },
  {
    id: "LA31",
    topic: "Linear Algebra (Cayley-Hamilton Theorem)",
    difficulty: 2850,
    problem: "Let MATRIX(A = [[3, 1], [2, 4]]). The Cayley-Hamilton theorem states that a matrix satisfies its own characteristic equation. If $A^2 - c_1 A - c_0 I = 0$, what is the value of $c_1$?",
    answer: "7",
  },
  {
    id: "LA35",
    topic: "Linear Algebra (Cramer's Rule)",
    difficulty: 1850,
    problem: "Use Cramer's Rule to solve for $x$ in the system: $2x+5y=1$ and $3x+7y=2$.",
    answer: "-3",
  },
  {
    id: "LA36",
    topic: "Linear Algebra (Vector Space Axioms)",
    difficulty: 2100,
    problem: "Which vector space axiom fails for the set of all pairs of real numbers $(x, y)$ with the operations $(x, y) + (x', y') = (x+x', y+y')$ and $c(x, y) = (cx, y)$? (e.g., 'closure under addition', 'distributivity', 'associativity')",
    answer: "distributivity",
  },
  {
    id: "LA37",
    topic: "Linear Algebra (Span)",
    difficulty: 1950,
    problem: "Does the vector $\\langle 1, 2, 3 \\rangle$ lie in the span of the vectors $\\{\\langle 1, 1, 1 \\rangle, \\langle 0, 1, 2 \\rangle\\}$? (yes/no)",
    answer: "no",
  },
  {
    id: "LA38",
    topic: "Linear Algebra (Rank-Nullity Theorem)",
    difficulty: 2050,
    problem: "A linear transformation $T: \\mathbb{R}^5 \\to \\mathbb{R}^3$ has a null space of dimension 2. What is the dimension of the range (image) of T?",
    answer: "3",
  },
  {
    id: "LA39",
    topic: "Linear Algebra (Change of Basis)",
    difficulty: 2500,
    problem: "In $\\mathbb{R}^2$, let basis $B = \\{ \\langle 1,1 \\rangle, \\langle 1,-1 \\rangle \\}$. The coordinates of a vector $x$ in the standard basis are $\\langle 4, 2 \\rangle$. What is the first coordinate of $x$ with respect to the basis $B$, i.e., $[x]_B = \\langle c_1, c_2 \\rangle$?",
    answer: "3",
  },
  {
    id: "LA40",
    topic: "Linear Algebra (Orthogonal Projection)",
    difficulty: 2200,
    problem: "Find the orthogonal projection of the vector $y = \\langle 7, 6 \\rangle$ onto the line spanned by the vector $u = \\langle 4, 2 \\rangle$. The projection is a vector $\\langle a, b \\rangle$. What is the value of $a$?",
    answer: "8",
  },
  {
    id: "LA41",
    topic: "Linear Algebra (Eigenvalues of Inverse)",
    difficulty: 2150,
    problem: "A $2 \\times 2$ matrix $A$ has eigenvalues 2 and 5. What is the largest eigenvalue of $A^{-1}$?",
    answer: "0.5",
  },
  {
    id: "LA42",
    topic: "Linear Algebra (Eigenvalues and Trace)",
    difficulty: 1950,
    problem: "A $3 \\times 3$ matrix has eigenvalues -1, 3, and 5. What is the trace of the matrix?",
    answer: "7",
  },
  {
    id: "LA43",
    topic: "Linear Algebra (Eigenvalues and Determinant)",
    difficulty: 2000,
    problem: "A $3 \\times 3$ matrix has eigenvalues -1, 3, and 5. What is the determinant of the matrix?",
    answer: "-15",
  },
  {
    id: "LA44",
    topic: "Linear Algebra (Diagonalization)",
    difficulty: 2700,
    problem: "Let MATRIX(A = [[1, 4], [1, 1]]). The matrix $A$ can be written as $PDP^{-1}$. The diagonal matrix $D$ contains the eigenvalues. What is the sum of the diagonal entries of $D$?",
    answer: "2",
  },
  {
    id: "LA45",
    topic: "Linear Algebra (Symmetric Matrices)",
    difficulty: 1800,
    problem: "If a matrix $A$ is symmetric, what is the relationship between $A$ and its transpose $A^T$? (e.g., A = -A^T, A = A^T, etc.)",
    answer: "A = A^T",
  },
  {
    id: "LA46",
    topic: "Linear Algebra (Orthogonal Matrices)",
    difficulty: 2400,
    problem: "Let $Q$ be an orthogonal $n \\times n$ matrix. What is the value of the determinant of $Q^T Q$?",
    answer: "1",
  },
  {
    id: "LA47",
    topic: "Linear Algebra (Positive Definite Matrices)",
    difficulty: 2800,
    problem: "Consider the symmetric matrix MATRIX(A = [[2, c], [c, 8]]). For what range of values of $c$ is this matrix positive definite?",
    answer: "-4 < c < 4",
  },
  {
    id: "LA48",
    topic: "Linear Algebra (QR Factorization)",
    difficulty: 2900,
    problem: "Let MATRIX(A = [[1, 1], [0, 1]]). $A=QR$ where Q is orthogonal and R is upper triangular with positive diagonal entries. Find the element in the first row, first column of R.",
    answer: "1",
  },
  {
    id: "LA49",
    topic: "Linear Algebra (Singular Value Decomposition - SVD)",
    difficulty: 2950,
    problem: "Let MATRIX(A = [[3, 0], [0, -2]]). Find the largest singular value of A.",
    answer: "3",
  },
  {
    id: "LA50",
    topic: "Linear Algebra (Adjacency Matrix)",
    difficulty: 2300,
    problem: "Consider a graph with 3 vertices {1, 2, 3} and edges (1,2), (2,3), and (3,1). Let A be its adjacency matrix. What is the trace of $A^2$?",
    answer: "6",
  },
  {
    id: "LA51",
    topic: "Linear Algebra (Markov Matrices)",
    difficulty: 2550,
    problem: "A certain Markov matrix has a steady-state vector $\\langle 0.6, 0.4 \\rangle$. What is the largest eigenvalue of this matrix?",
    answer: "1",
  },
  {
    id: "LA52",
    topic: "Linear Algebra (Complex Eigenvalues)",
    difficulty: 2650,
    problem: "The rotation matrix MATRIX(R = [[0, -1], [1, 0]]) rotates vectors by 90 degrees counter-clockwise. What is the eigenvalue with a positive imaginary part?",
    answer: "i",
  },
  {
    id: "LA53",
    topic: "Linear Algebra (Projection Matrix)",
    difficulty: 2750,
    problem: "Let $P$ be the matrix that projects vectors in $\\mathbb{R}^3$ onto the xy-plane. What is the determinant of $P$?",
    answer: "0",
  },
  {
    id: "LA54",
    topic: "Linear Algebra (Isomorphism)",
    difficulty: 2450,
    problem: "The vector space $P_3$ of polynomials of degree at most 3 is isomorphic to which Euclidean space $\\mathbb{R}^n$?",
    answer: "R⁴",
  },
  {
    id: "LA55",
    topic: "Linear Algebra (Inner Product Space)",
    difficulty: 2600,
    problem: "In the space $C[0,1]$ of continuous functions on $[0,1]$, the inner product is defined as $\\langle f, g \\rangle = \\int_0^1 f(x)g(x)dx$. Find the inner product of $f(x)=1$ and $g(x)=x$.",
    answer: "0.5",
  },
  {
    id: "LA56",
    topic: "Linear Algebra (Matrix Exponential)",
    difficulty: 3000,
    problem: "Let MATRIX(A = [[1, 1], [0, 1]]). Compute the matrix exponential $e^{At}$. What is the element in the first row, second column at $t=1$?",
    answer: "e",
  },
{
  id: "LA77",
  topic: "Linear Algebra (Linear Independence)",
  difficulty: 1750,
  problem: "Are the vectors $\\langle 1, 2, 3 \\rangle$, $\\langle 4, 5, 6 \\rangle$, and $\\langle 7, 8, 9 \\rangle$ linearly independent? (yes/no)",
  answer: "no",
},
{
  id: "LA78",
  topic: "Linear Algebra (Subspace)",
  difficulty: 1900,
  problem: "Is the set of all vectors $\\langle x, y \\rangle$ in $\\mathbb{R}^2$ such that $x \\ge 0$ a subspace of $\\mathbb{R}^2$? (yes/no)",
  answer: "no",
},
{
  id: "LA79",
  topic: "Linear Algebra (Basis)",
  difficulty: 1800,
  problem: "What is the dimension of the vector space $P_4$, the set of all polynomials of degree at most 4?",
  answer: "5",
},
{
  id: "LA80",
  topic: "Linear Algebra (Column Space)",
  difficulty: 2050,
  problem: "Find a basis for the column space of MATRIX(A = [[1, 2], [3, 6]]). What is the dimension of this space?",
  answer: "1",
},
{
  id: "LA81",
  topic: "Linear Algebra (Null Space)",
  difficulty: 2100,
  problem: "Find the dimension of the null space (kernel) of MATRIX(A = [[1, 2, 3], [0, 1, 2], [0, 0, 0]]).",
  answer: "1",
},
{
  id: "LA82",
  topic: "Linear Algebra (Rank-Nullity Theorem)",
  difficulty: 2000,
  problem: "A $5 \\times 7$ matrix $A$ has a null space of dimension 3. What is the rank of $A$?",
  answer: "4",
},
{
  id: "LA83",
  topic: "Linear Algebra (Orthogonality)",
  difficulty: 1600,
  problem: "Find the value of $k$ such that the vectors $\\langle 1, k, 3 \\rangle$ and $\\langle 2, -4, 2 \\rangle$ are orthogonal.",
  answer: "2",
},
{
  id: "LA84",
  topic: "Linear Algebra (Vector Norm)",
  difficulty: 1300,
  problem: "Find the length (magnitude) of the vector $v = \\langle 3, 0, -4 \\rangle$.",
  answer: "5",
},
{
  id: "LA85",
  topic: "Linear Algebra (Eigenvalues)",
  difficulty: 1950,
  problem: "Find the sum of the eigenvalues of the matrix MATRIX(A = [[3, 2], [1, 4]]).",
  answer: "7",
},
{
  id: "LA86",
  topic: "Linear Algebra (Eigenvector Check)",
  difficulty: 1700,
  problem: "Is $\\langle 1, 1 \\rangle$ an eigenvector of the matrix MATRIX(A = [[2, 1], [1, 2]])? (yes/no)",
  answer: "yes",
},
{
  id: "LA87",
  topic: "Linear Algebra (Eigenvalues of Triangular Matrix)",
  difficulty: 1500,
  problem: "What are the eigenvalues of the matrix MATRIX(A = [[-1, 2, 4], [0, 5, 8], [0, 0, -3]])? (Enter the smallest value).",
  answer: "-3",
},
{
  id: "LA88",
  topic: "Linear Algebra (Diagonalization)",
  difficulty: 2500,
  problem: "Is the matrix MATRIX(A = [[1, 1], [0, 1]]) diagonalizable? (yes/no)",
  answer: "no",
},
{
  id: "LA89",
  topic: "Linear Algebra (Change of Basis)",
  difficulty: 2600,
  problem: "Let $B = \\{\\langle 1, 0 \\rangle, \\langle 1, 1 \\rangle\\}$ be a basis for $\\mathbb{R}^2$. The vector $v = \\langle 3, 2 \\rangle$ can be written as $c_1b_1 + c_2b_2$. What is $c_1$?",
  answer: "1",
},
{
  id: "LA90",
  topic: "Linear Algebra (Projection)",
  difficulty: 2200,
  problem: "Find the scalar projection of $b = \\langle 2, 3 \\rangle$ onto $a = \\langle 1, 1 \\rangle$.",
  answer: "5/√2",
},
{
  id: "LA91",
  topic: "Linear Algebra (Gram-Schmidt)",
  difficulty: 2700,
  problem: "Apply the Gram-Schmidt process to the vectors $v_1 = \\langle 3, 0 \\rangle$ and $v_2 = \\langle 1, 2 \\rangle$ to get an orthogonal basis $\{u_1, u_2\}$. What is the second vector, $u_2$?",
  answer: "<0, 2>",
},
{
  id: "LA92",
  topic: "Linear Algebra (Orthogonal Matrix)",
  difficulty: 2350,
  problem: "Let $Q$ be an orthogonal matrix. If $v$ is a column vector, what is the length of $Qv$ compared to the length of $v$? (e.g., 'longer', 'shorter', 'same')",
  answer: "same",
},
{
  id: "LA93",
  topic: "Linear Algebra (Least Squares)",
  difficulty: 2800,
  problem: "Find the least-squares line $y = \\beta_0 + \\beta_1 x$ that best fits the data points (0,1), (1,2), and (2,4). What is the value of the slope, $\\beta_1$?",
  answer: "1.5",
},
{
  id: "LA94",
  topic: "Linear Algebra (Inner Product Space)",
  difficulty: 2650,
  problem: "In the vector space $P_2$ with inner product $\\langle p, q \\rangle = \\int_{-1}^1 p(x)q(x)dx$, are the polynomials $p(x)=1$ and $q(x)=x$ orthogonal? (yes/no)",
  answer: "yes",
},
{
  id: "LA95",
  topic: "Linear Algebra (Spectral Theorem)",
  difficulty: 2450,
  problem: "According to the Spectral Theorem, a real symmetric matrix is always... (one word)",
  answer: "diagonalizable",
},
{
  id: "LA96",
  topic: "Linear Algebra (Singular Values)",
  difficulty: 2950,
  problem: "Find the singular values of the matrix MATRIX(A = [[0, 2], [0, 0]]). What is the largest singular value?",
  answer: "2",
}
];