// A huge list of calculus and linear algebra problems.
// Format: { id, topic, difficulty, problem, answer }
// Difficulty is an ELO-style rating from ~1000 to ~3000.
// MATH is wrapped in $...$ for KaTeX rendering.

export const mathProblems = [
  // --- Calculus I: Derivatives ---
  {
    id: "C01",
    topic: "Calculus (Basic Derivative)",
    difficulty: 1100,
    problem: "Let $f(x) = 5x^3 - 7x^2 + 2x - 10$. Find the value of $f'(2)$.",
    answer: "34",
  },
  {
    id: "C02",
    topic: "Calculus (Product Rule)",
    difficulty: 1350,
    problem: "Let $h(x) = x^2 \\cdot \\sin(x)$. Find the value of $h'(\\pi)$.",
    answer: "-π²",
  },
  {
    id: "C03",
    topic: "Calculus (Quotient Rule)",
    difficulty: 1450,
    problem: "Let $f(x) = \\frac{2x - 1}{x^2 + 1}$. Find the value of $f'(1)$.",
    answer: "0.5",
  },
  {
    id: "C04",
    topic: "Calculus (Chain Rule)",
    difficulty: 1500,
    problem: "Let $g(x) = (x^3 + 3)^4$. Find the value of $g'(1)$.",
    answer: "768",
  },
  {
    id: "C05",
    topic: "Calculus (Chain Rule with Trig)",
    difficulty: 1600,
    problem: "Let $f(x) = \\cos(\\pi x^2)$. Find the value of $f'(1)$.",
    answer: "0",
  },
  {
    id: "C06",
    topic: "Calculus (Implicit Differentiation)",
    difficulty: 1850,
    problem: "For the circle defined by $x^2 + y^2 = 25$, find the slope of the tangent line ($\\frac{dy}{dx}$) at the point $(3, -4)$.",
    answer: "0.75",
  },

  // --- Calculus II: Integrals ---
  {
    id: "C10",
    topic: "Calculus (Definite Integral)",
    difficulty: 1250,
    problem: "Evaluate the definite integral of $f(x) = 3x^2 + 4x$ from $x=0$ to $x=2$. That is, find $\\int_0^2 (3x^2+4x)dx$.",
    answer: "16",
  },
  {
    id: "C11",
    topic: "Calculus (U-Substitution)",
    difficulty: 1550,
    problem: "Evaluate $\\int_0^1 x(x^2 + 1)^3 dx$.",
    answer: "3.75",
  },
  {
    id: "C12",
    topic: "Calculus (Integration by Parts)",
    difficulty: 1650,
    problem: "Evaluate $\\int_1^e x \\ln(x) dx$.",
    answer: "(e²+1)/4",
  },
  {
    id: "C13",
    topic: "Calculus (Improper Integral)",
    difficulty: 1900,
    problem: "Evaluate the improper integral $\\int_1^\\infty \\frac{1}{x^2} dx$.",
    answer: "1",
  },
  {
    id: "C14",
    topic: "Calculus (Trigonometric Substitution)",
    difficulty: 2100,
    problem: "Evaluate $\\int_0^2 \\sqrt{4 - x^2} dx$.",
    answer: "π",
  },
  {
    id: "C15",
    topic: "Calculus (Partial Fractions)",
    difficulty: 2200,
    problem: "Evaluate $\\int_0^1 \\frac{1}{x^2 + 3x + 2} dx$.",
    answer: "ln(4/3)",
  },

  // --- Calculus III & Advanced Topics ---
  {
    id: "C20",
    topic: "Calculus (Partial Derivative)",
    difficulty: 1700,
    problem: "Let $f(x, y) = x^3y^2 - 2xy + 5y$. Find the value of the partial derivative $\\frac{\\partial f}{\\partial x}$ at the point $(2, 3)$.",
    answer: "102",
  },
  {
    id: "C21",
    topic: "Calculus (Gradient)",
    difficulty: 1800,
    problem: "Let $f(x, y) = x^2 + y^2$. Find the magnitude of the gradient vector, $|\\nabla f|$, at the point $(3, 4)$.",
    answer: "10",
  },
  {
    id: "C22",
    topic: "Calculus (Directional Derivative)",
    difficulty: 1950,
    problem: "Find the directional derivative of $f(x, y) = e^{xy}$ at the point $(1, 2)$ in the direction of the vector $v = \\langle 3, 4 \\rangle$.",
    answer: "(11/5)*e²",
  },
  {
    id: "C23",
    topic: "Calculus (Double Integral)",
    difficulty: 2050,
    problem: "Evaluate the double integral of $f(x, y) = 6xy$ over the rectangular region $R$ where $0 \\le x \\le 2$ and $0 \\le y \\le 1$.",
    answer: "6",
  },
  {
    id: "C24",
    topic: "Calculus (Triple Integral)",
    difficulty: 2400,
    problem: "Use a triple integral in spherical coordinates to find the volume of a sphere with radius $R=3$.",
    answer: "36π",
  },
  {
    id: "C25",
    topic: "Calculus (Line Integral)",
    difficulty: 2300,
    problem: "Evaluate the line integral $\\int_C (x+y) ds$ where $C$ is the line segment from $(0,0)$ to $(1,2)$.",
    answer: "3√5 / 2",
  },
  {
    id: "C26",
    topic: "Calculus (Line Integral)",
    difficulty: 2500,
    problem: "Let $F(x,y) = \\langle y, -x \\rangle$. Calculate the work done ($\\int_C F \\cdot dr$) along the path $C$, the top half of the unit circle $x^2+y^2=1$ from $(1,0)$ to $(-1,0)$.",
    answer: "-π",
  },
  {
    id: "C27",
    topic: "Calculus (Curl of a Vector Field)",
    difficulty: 2600,
    problem: "Let the vector field $F = \\langle yz, xz, xy \\rangle$. Find the magnitude of the curl of $F$, $|\\nabla \\times F|$, at the point $(1, 2, 3)$.",
    answer: "0",
  },
  {
    id: "C28",
    topic: "Calculus (Divergence)",
    difficulty: 2550,
    problem: "Let the vector field $F = \\langle x^3, y^3z, x^2y \\rangle$. Find the divergence of $F$, $\\nabla \\cdot F$, at the point $(2, 1, -1)$.",
    answer: "9",
  },
  {
    id: "C29",
    topic: "Calculus (Green's Theorem)",
    difficulty: 2700,
    problem: "Use Green's Theorem to evaluate the line integral $\\oint_C (y^2 dx + 3xy dy)$ where $C$ is the boundary of the square with vertices $(0,0), (1,0), (1,1),$ and $(0,1)$, traversed counter-clockwise.",
    answer: "0.5",
  },
  {
    id: "C30",
    topic: "Calculus (Stokes' Theorem)",
    difficulty: 2950,
    problem: "Let $F = \\langle y, z, x \\rangle$. Let $S$ be the surface of the plane $2x + y + 2z = 2$ in the first octant. What is the value of the surface integral $\\iint_S (\\nabla \\times F) \\cdot dS$?",
    answer: "-1.5",
  },
  {
    id: "C31",
    topic: "Calculus (Geometric Series)",
    difficulty: 1700,
    problem: "What is the sum of the infinite geometric series $\\sum_{n=0}^{\\infty} (\\frac{2}{3})^n$?",
    answer: "3",
  },
  {
    id: "C32",
    topic: "Calculus (Taylor Series)",
    difficulty: 2000,
    problem: "Let $f(x) = e^x$. Find the coefficient of the $x^3$ term in the Maclaurin series expansion of $f(x)$.",
    answer: "1/6",
  },
  {
    id: "C33",
    topic: "Calculus (L'Hôpital's Rule)",
    difficulty: 1900,
    problem: "Evaluate the limit $\\lim_{x \\to 0} \\frac{\\sin(x) - x}{x^3}$.",
    answer: "-1/6",
  },
  {
    id: "C34",
    topic: "Calculus (Volume of Revolution)",
    difficulty: 1800,
    problem: "Find the volume of the solid generated by revolving the region bounded by $y = \\sqrt{x}$, $y = 0$, and $x = 4$ about the x-axis.",
    answer: "8π",
  },
  {
    id: "C35",
    topic: "Calculus (Arc Length)",
    difficulty: 2250,
    problem: "Find the arc length of the curve $y = \\frac{2}{3}x^{3/2}$ from $x=0$ to $x=3$.",
    answer: "14/3",
  },

  // --- Linear Algebra: Basic Operations ---
  {
    id: "LA01",
    topic: "Linear Algebra (Matrix Multiplication)",
    difficulty: 1200,
    problem: "Let MATRIX(A = [[1, 2], [3, 4]]) and MATRIX(B = [[2, 0], [1, 3]]). Find the element in the first row, first column of the product $AB$.",
    answer: "4",
  },
  {
    id: "LA02",
    topic: "Linear Algebra (Matrix Transpose)",
    difficulty: 1150,
    problem: "Let MATRIX(C = [[1, 2, 3], [4, 5, 6]]). Find the element in the second row, first column of the transpose $C^T$.",
    answer: "2",
  },
  {
    id: "LA03",
    topic: "Linear Algebra (Dot Product)",
    difficulty: 1050,
    problem: "Find the dot product of the vectors $u = \\langle 2, -3, 5 \\rangle$ and $v = \\langle 1, 4, -2 \\rangle$.",
    answer: "-20",
  },
  {
    id: "LA04",
    topic: "Linear Algebra (Determinant 2x2)",
    difficulty: 1300,
    problem: "Find the determinant of the matrix MATRIX(A = [[-5, 3], [2, 1]]).",
    answer: "-11",
  },
  {
    id: "LA05",
    topic: "Linear Algebra (Determinant 3x3)",
    difficulty: 1750,
    problem: "Find the determinant of the matrix MATRIX(A = [[1, 2, 3], [0, 4, 5], [1, 0, 6]]).",
    answer: "22",
  },
  {
    id: "LA06",
    topic: "Linear Algebra (Matrix Inverse 2x2)",
    difficulty: 1650,
    problem: "Let MATRIX(A = [[4, 7], [2, 3]]). Find the element in the second row, second column of the inverse matrix $A^{-1}$.",
    answer: "-2",
  },
  
  // --- Linear Algebra: Vector Spaces & Eigenvalues ---
  {
    id: "LA10",
    topic: "Linear Algebra (Linear Independence)",
    difficulty: 1800,
    problem: "Consider the vectors $v_1=\\langle 1,0,1 \\rangle$, $v_2=\\langle 0,1,1 \\rangle$, and $v_3=\\langle 1,1,k \\rangle$. For what value of $k$ are these three vectors linearly dependent?",
    answer: "2",
  },
  {
    id: "LA11",
    topic: "Linear Algebra (Eigenvalues 2x2)",
    difficulty: 1900,
    problem: "Find the largest eigenvalue of the matrix MATRIX(A = [[2, 7], [1, 8]]).",
    answer: "9",
  },
  {
    id: "LA12",
    topic: "Linear Algebra (Eigenvalues 3x3)",
    difficulty: 2250,
    problem: "The matrix MATRIX(A = [[2, 0, 0], [1, 2, 1], [-1, 0, 1]]) is triangular. What is the sum of its eigenvalues?",
    answer: "5",
  },
  {
    id: "LA13",
    topic: "Linear Algebra (Eigenvector)",
    difficulty: 2150,
    problem: "The matrix MATRIX(A = [[3, 1], [1, 3]]) has an eigenvalue of $\\lambda=4$. An eigenvector corresponding to this eigenvalue is $\\langle k, 1 \\rangle$. What is the value of $k$?",
    answer: "1",
  },
  {
    id: "LA14",
    topic: "Linear Algebra (Diagonalization)",
    difficulty: 2650,
    problem: "Let MATRIX(A = [[1, 2], [0, 3]]). $A$ is diagonalizable as $A = PDP^{-1}$, where $D$ is a diagonal matrix of eigenvalues. What is the value in the second row, second column of $D$? (Assume eigenvalues are ordered from smallest to largest).",
    answer: "3",
  },
  {
    id: "LA15",
    topic: "Linear Algebra (Orthogonality)",
    difficulty: 1950,
    problem: "For what value of 'c' are the vectors $u = \\langle 2, c, -4 \\rangle$ and $v = \\langle 3, -1, 1 \\rangle$ orthogonal?",
    answer: "2",
  },
  {
    id: "LA16",
    topic: "Linear Algebra (Projection)",
    difficulty: 2350,
    problem: "Find the magnitude of the projection of vector $u = \\langle 1, 2, 2 \\rangle$ onto vector $v = \\langle 1, 1, 1 \\rangle$.",
    answer: "5/√3",
  },
  {
    id: "LA17",
    topic: "Linear Algebra (System of ODEs)",
    difficulty: 2800,
    problem: "Consider the system of linear differential equations $x' = Ax$ where MATRIX(A = [[0, 1], [-10, -7]]). What is the real part of the eigenvalue with the larger imaginary part?",
    answer: "-3.5",
  },
  {
    id: "LA18",
    topic: "Linear Algebra (Change of Basis)",
    difficulty: 2750,
    problem: "In $\\mathbb{R}^2$, let $B = \\{ \\langle 1,1 \\rangle, \\langle 0,2 \\rangle \\}$ be a basis. What is the determinant of the change-of-basis matrix from $B$ to the standard basis?",
    answer: "2",
  },
  {
    id: "LA19",
    topic: "Linear Algebra (Rank)",
    difficulty: 2000,
    problem: "What is the rank of the matrix MATRIX(A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]])?",
    answer: "2",
  },
];